apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-consumer5
  labels:
    app: hello-world-consumer5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-consumer5
  template:
    metadata:
      labels:
        app: hello-world-consumer5
    spec:
      containers:
      - name: hello-world-consumer
        image: strimzi/hello-world-consumer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: my-topic
          - name: GROUP_ID
            value: my-hello-world-consumer5
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
